### ISSUE TITLE
Curious when the Jupyter Hub python container will match the image definitions

### ISSUE THREAD

**Issue by mojsiloo** [microsoft/planetary-computer-containers#31]
Hi, 

Wasn't sure where to post this, but I noticed that the python environment on the Jupyter Hub doesn't yet match the package versions in conda lock file.

For example, the conda lock file set-up has stackstac==0.4.0, yet I'm seeing version 0.3.1 of stackstac on the hub environment.

Does it some time for the container filers to be updated? 

Thanks, Ogi

**Comment by TomAugspurger** [comment]
Indeed, there's some delay. The versions on the Hub are updated with releases to github/planetary-computer-hub. If we look at https://github.com/microsoft/planetary-computer-hub/blob/2022.02.14.0/terraform/prod/main.tf#L25, we see it's pointing back to the 2022.02.14.0 release here (https://github.com/microsoft/planetary-computer-containers/blob/2022.02.14.0/python/conda-linux-64.lock). It's a bit convoluted and I'd like to have a static page with the versions on them someday.

We typically update the versions used on the Hub along with our quarterly releases.

**Comment by mojsiloo** [comment]
Thanks for the answer Tom
