### ISSUE TITLE
GPU option with tensorflow

### ISSUE THREAD

**Issue by zstatmanweil** [microsoft/planetary-computer-containers#6]
As a team that is using Planetary Computer but relies on Tensorflow for our ML modeling work, it would be great to have a GPU option with Tensorflow (v 2.4.0 or above) so we can easily access PC data and develop models in one place. I tried installing tensorflow into the current GPU option but it doesn't end up working because the CUDA development and runtime libraries aren't installed. On a related note, it would be great to have Tensorflow in the python CPU option as well. 

Thanks!

**Comment by TomAugspurger** [comment]
Thanks for raising an issue. I'll see if I can get an image with TF + Keras + jax, in addition to the usual libraries. Anything else?

> On a related note, it would be great to have Tensorflow in the python CPU option as well.

Yeah, I'm trying to keep the image sizes of the base Python image somewhat reasonable. I haven't looked at what just Tensorflow (not cuda) does to the size of the image, but I'm imagining it'll increase their size significantly.

**Comment by TomAugspurger** [comment]
See https://github.com/microsoft/planetary-computer-containers/pull/7

If you could let me know whether you have any other libraries that you'd consider "core" when doing geospatial ML with tensorfow, I'll see if they can be added as well.

**Comment by zstatmanweil** [comment]
This is awesome to hear! I know we end up installing `rio-tiler` a lot so as of now that would be our other request to this image (and the CPU one) but I respect you want to keep these images light. Tensorflow+GPU is definitely our number one priority. 

> Yeah, I'm trying to keep the image sizes of the base Python image somewhat reasonable. I haven't looked at what just Tensorflow (not cuda) does to the size of the image, but I'm imagining it'll increase their size significantly.

This makes sense. I think installing `tensorflow-cpu` ourselves won't be a problem.

**Comment by zstatmanweil** [comment]
And you already opened a PR! This is amazing and will make our lives a lot easier.

**Comment by TomAugspurger** [comment]
Great, I'll add rio-tiler to the images. I'll get that added and merged and we'll see if any issues come up during the build.

**Comment by zstatmanweil** [comment]
Wow! Amazing! Looks like the build worked. So I should Look out for it under the "Choose your environment" option when you login to Hub?

**Comment by TomAugspurger** [comment]
Yeah, that's being added at https://github.com/microsoft/planetary-computer-hub/pull/11 (to our staging deployment). If things look OK with some manual testing I'll deploy to production and it should show up for you.

**Comment by TomAugspurger** [comment]
I'm running into some issues with that in staging unfortunately :( I'll take a look tomorrow or Monday morning though!

**Comment by zstatmanweil** [comment]
Understandable :-) Thanks again for jumping on this so quick!

**Comment by zstatmanweil** [comment]
@TomAugspurger , I saw the new option in the Hub this morning. Wahoo! I do get an authorization error related to pulling the image when I try to launch it: 

![image](https://user-images.githubusercontent.com/37987755/135897984-92cd4775-ea82-4da5-a83e-2dd983df393b.png)

**Comment by TomAugspurger** [comment]
Yeah I noticed that too 😬. Fixed in https://github.com/microsoft/planetary-computer-hub/pull/14/files#diff-1c45f90b87a9db6b9e68d9a5525d0a664f3c0120562b55f11617a4162fdbf692L27

An unrelated issue is making this difficult to test on the staging cluster, so I'm having to test it in production. Hopefully the current update fixes it.

**Comment by TomAugspurger** [comment]
@zstatmanweil do you want to give it another shot now?

```
>>> import tensorflow as tf
>>> tf.test.gpu_device_name()
```
prints out a bunch of stuff, but returns `'/device:GPU:0'` which I think means the GPU is active. Could you let me know if this covers your needs?

**Comment by zstatmanweil** [comment]
It appears to be working! I was able to launch the environment, and check the GPU is active and all that returned info looks how I would expect. Thank you again. If we have any troubles once we start doing substantial work with it, I will open another issue.
